name: Test Project 
on: push
jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
            - name: code repo
              uses: actions/checkout@v4
            
            - name: installing nodejs 18
              uses: actions/setup-node@v4

            - name: installing dependcies
              run: npm ci

            - name: running test 
              run: npm test 
