name: demi workflow
on: workflow_dispatch 
jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world
              run: |
                  echo "Hello World"
                  echo "Good Bye World"
